### ISSUE TITLE
Correcion

### ISSUE THREAD

**Issue by marcosdgl** [GonzaRom/Guia_Lab3_Objetos1#1]
Gonza, como estas? La guia en gral esta bien! dejo unas correciones que vi.

No esta bueno definir los attr en linea, pq tenes que hacer un constructor para cada obj que creas, la idea es pasarlo por parametro asi lo definis al momento de instanciar. ej.
`public Empleado(int dni, String apellido, double salario, String nombre) { `
`   this.apellido = apellido;`
`   this.dni = dni;`
`   this.salario = salario;`
`   this.nombre = nombre;`
`}`
(si se pide crear el obj con solo un parametro se puede utilizar el costructor vacio y los setters para no hardcodear en el costructor)
https://github.com/GonzaRom/Guia_Lab3_Objetos1/blob/44098f0621a14f35502844e0ced7de3dcf586b08/src/com/clases/Empleado.java#L10
Aca tenes el problema que si ya son 59 los min va a seguir sumando en vez de modificar la hora. (si usas el setter que creaste deberia funcionar en vez de ++minutos)
https://github.com/GonzaRom/Guia_Lab3_Objetos1/blob/44098f0621a14f35502844e0ced7de3dcf586b08/src/com/clases/Hora.java#L52
trata de usar nombres representativos (no es necesario abreviar), ahora parece sin importancia pero en un futuro te ahorra tiempo y dolores de cabeza.
https://github.com/GonzaRom/Guia_Lab3_Objetos1/blob/44098f0621a14f35502844e0ced7de3dcf586b08/src/com/guia1_poo/Main.java#L71

Cualquier cosa no dudes en consultarme. 
Saludos

**Comment by GonzaRom** [comment]
Marcos, excelentes aclaraciones!
Este tipo de errores son los que terminó llevando a un examen, por ejemplo y me terminan complicando. 

Voy a tenerlos en cuenta. 

Gracias por el feedback.
